### ISSUE TITLE
NPM version is outdated

### ISSUE THREAD

**Issue by mssalnikov** [lamualfa/i18next-node-mongodb-backend-next#14]
The current master fix "collection doesn't exist" is a very nasty one to have in the currently published 0.0.4 version. I can't use this library in production because of this

**Comment by emanuelet** [comment]
same here. I had to fork it to be able to use it

**Comment by lamualfa** [comment]
Sorry for the delay. I've been a bit busy lately.

Anyway, The new features has been added in [v0.0.5](https://www.npmjs.com/package/i18next-node-mongodb-backend-next). The package name has been renamed from `i18next-node-mongo-backend` to `i18next-node-mongodb-backend-next`. So carefully.

I am sorry.

<hr>

If anyone wants to be a volunteer maintainer, I really appreciate it. I will make it the admin of this repository. Thanks.
