### ISSUE TITLE
Problem when adding a new key into database

### ISSUE THREAD

**Issue by salarihamid** [lamualfa/i18next-node-mongodb-backend-next#19]
i recently updated to v1.0.1

when the system cant find a key and trying to add the key into ' dev ' language , there is an error .

the create function if not checking if there is a " cb " available to call it .

at line 214 index.js file , your calling the cb() and there is no cb provided , so the code crash .

i recommend using : 

```
if (cb) cb(); 
```

**Comment by lamualfa** [comment]
merged https://github.com/lamualfa/i18next-node-mongodb-backend-next/pull/20

**Comment by lamualfa** [comment]
The new version just released:

https://github.com/lamualfa/i18next-node-mongodb-backend-next/releases/tag/v1.0.2
